Let the user choose the language with a select-box instead of typing the language code into a input-field.
Saibamen/ReactOS-Translation-Tool pull request #9
Opened 2021-04-12 16:39 UTC by gonzoMD

* Add langcodes.php which contains an array that holds the ISO 639-1 data
* Use a select-box in index.php, encoding.php and diff.php instead of an input-field
* Change some texts accordingly

2021-04-13 00:13 UTC, Saibamen requested changes

2021-04-13 00:13 UTC, Saibamen commented on index.php
> +                    <select id="lang" name="lang" class="form-control">
Please add removed `required="required"`

2021-04-13 00:13 UTC, Saibamen commented on index.php
> +                        <option value="" selected disabled hidden>Choose here</option>
Delete `selected` and use it in `foreach` loop - depending on `$_SESSION['lang']`

2021-04-13 00:13 UTC, Saibamen commented on index.php
> +}?>
Fix identation

2021-04-13 00:13 UTC, Saibamen commented on langcodes.php
> +// Data taken from: https://beta.wikiversity.org/wiki/List_of_ISO_639-1_codes
Please add additional comment like `// Last updated: 13.04.2021`

2021-04-14 07:44 UTC, gonzoMD commented
all done. but after fixing the indent styleci goes nuts.

2021-04-14 15:46 UTC, Saibamen requested changes

2021-04-14 15:46 UTC, Saibamen commented on diff.php
> +                        echo"> $language[1]</option>";
```suggestion
                        echo '<option value="'. $language[0] .'" ';
                        if (isset($_SESSION['lang']) && ($language[0] == $_SESSION['lang'])) echo 'selected';
                        echo '> $language[1]</option>';
```

2021-04-14 15:46 UTC, Saibamen commented on encoding.php
> +                        echo"> $language[1]</option>";
```suggestion
                        echo '<option value="'. $language[0] .'" ';
                        if (isset($_SESSION['lang']) && ($language[0] == $_SESSION['lang'])) echo 'selected';
                        echo '> $language[1]</option>';
```

2021-04-14 15:46 UTC, Saibamen commented on index.php
> +                        echo"> $language[1]</option>";
```suggestion
                        echo '<option value="'. $language[0] .'" ';
                        if (isset($_SESSION['lang']) && ($language[0] == $_SESSION['lang'])) echo 'selected';
                        echo '> $language[1]</option>';
```

2021-04-14 16:25 UTC, Saibamen commented on diff.php
> +                        echo '<option value="'. $language[0] .'" ';
```suggestion
                        echo '<option value="'.$language[0].'" ';
```

2021-04-14 16:25 UTC, Saibamen commented on encoding.php
> +                        echo '<option value="'. $language[0] .'" ';
```suggestion
                        echo '<option value="'.$language[0].'" ';
```

2021-04-14 16:25 UTC, Saibamen commented on index.php
> +                        echo '<option value="'. $language[0] .'" ';
```suggestion
                        echo '<option value="'.$language[0].'" ';
```

2021-04-14 21:07 UTC, merged

2021-04-14 21:16 UTC, Saibamen commented
Merged. Thanks